name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/ci-b.yml"
      - "build.gradle"
      - "settings.gradle"
      - "gradle/**"
      - "gradlew*"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/ci-b.yml"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build & Test (all subprojects)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            clean build
          build-root-directory: .

      - name: Upload JARs (artifact)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: backend-jars
          path: |
            backend/**/build/libs/*.jar
